package trabalho.conclusao;
//
//Automatically generated by XACDML
//

import simula.manager.*;
public class SCSI
{
 public static void main (String args[])
 {
  System.out.println("\nGeracao de SCSI atraves de Simulation Manager");
  SimulationManager man= new SimulationManager();

  QueueEntry qe;//queues 
  ResourceEntry re;//resource queues
  ExternalActiveEntry eae;//generator and detroy
  InternalActiveEntry iae;//activivity and router
  InterruptActiveEntry intae;//interrupts
  ObserverEntry oe;
  HistogramEntry he;

  //queues and observer queues
  

  qe = new QueueEntry();
  qe.SetId("Q_A1");//mapped by dead id
  qe.setObsid("Q_A1_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_A2");//mapped by dead id
  qe.setObsid("Q_A2_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_A3");//mapped by dead id
  qe.setObsid("Q_A3_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_FB1");//mapped by dead id
  qe.setObsid("Q_FB1_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_FB2");//mapped by dead id
  qe.setObsid("Q_FB2_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_FB3");//mapped by dead id
  qe.setObsid("Q_FB3_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_FB4");//mapped by dead id
  qe.setObsid("Q_FB4_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_FB5");//mapped by dead id
  qe.setObsid("Q_FB5_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_FB6");//mapped by dead id
  qe.setObsid("Q_FB6_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_GENERATE_CONTROL_ACTION");//mapped by dead id
  qe.setObsid("Q_GEN_CONTROL_ACTION_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_GENERATE_API_DATA");//mapped by dead id
  qe.setObsid("Q_GEN_API_DATA_OBS");//observer
  man.AddQueue(qe);
  

  qe = new QueueEntry();
  qe.SetId("Q_CONTROL_ALG");//mapped by dead id
  qe.setObsid("Q_CONTROL_ALG_OBS");//observer
  man.AddQueue(qe);
  
  re = new ResourceEntry();
  re.SetId("TRAFFIC_AGENT");//mapped by dead id
  re.setInit((short) 1);
  man.AddResource(re);
  re = new ResourceEntry();
  re.SetId("SCCI_MODULE");//mapped by dead id
  re.setInit((short) 1);
  man.AddResource(re);
  re = new ResourceEntry();
  re.SetId("TRAFFIC_LIGHTS");//mapped by dead id
  re.setInit((short) 2);
  man.AddResource(re);
  re = new ResourceEntry();
  re.SetId("N_TRAFFIC_SENSOR_1");//mapped by dead id
  re.setInit((short) 1);
  man.AddResource(re);
  re = new ResourceEntry();
  re.SetId("N_TRAFFIC_SENSOR_2");//mapped by dead id
  re.setInit((short) 1);
  man.AddResource(re);
  re = new ResourceEntry();
  re.SetId("P_TRAFFIC_SENSOR_1");//mapped by dead id
  re.setInit((short) 1);
  man.AddResource(re);
  re = new ResourceEntry();
  re.SetId("P_TRAFFIC_SENSOR_2");//mapped by dead id
  re.setInit((short) 1);
  man.AddResource(re);
  re = new ResourceEntry();
  re.SetId("INTERSECTION");//mapped by dead id
  re.setInit((short) 1);
  man.AddResource(re);
  //active states

   //externals (generates and destroys)
  
  eae = new ExternalActiveEntry(true); //generate
  eae.SetId("GENERATE_CONTROL_ACTION"); //mapped by generate id
  eae.setQID("Q_GENERATE_CONTROL_ACTION"); // mapped by next dead
  eae.setServiceDist( ActiveEntry.NEGEXP);// mapped by stat type
  eae.setDistP1((int)40.5);// mapped by parm1
  man.AddActiveState(eae);
  
  eae = new ExternalActiveEntry(true); //generate
  eae.SetId("GENERATE_API"); //mapped by generate id
  eae.setQID("Q_GENERATE_API_DATA"); // mapped by next dead
  eae.setServiceDist( ActiveEntry.POISSON);// mapped by stat type
  eae.setDistP1((int)60.0);// mapped by parm1
  man.AddActiveState(eae);
  

   //internals (activities and routers)

  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_CONTROL_ALG"); //mapped by act id
  iae.setServiceDist(ActiveEntry.CONST);// mapped by stat type
  iae.setDistP1((int)1.1);// mapped by parm1
  iae.addCond("true");
  iae.addToQueue("Q_CONTROL_ALG");// mapped by next dead
  iae.addFromQueue("Q_A1");// mapped by prev dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_A1"); //mapped by act id
  iae.setServiceDist(ActiveEntry.NORMAL);// mapped by stat type
  iae.setDistP1((int)20);// mapped by parm1
  iae.setDistP2((int)10); //mapped by parm2
  iae.addCond("true");
  iae.addToQueue("Q_A1");// mapped by next dead
  iae.addFromQueue("Q_FB1");// mapped by prev dead
  iae.addToResource("TRAFFIC_AGENT");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("TRAFFIC_AGENT");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_A2.1"); //mapped by act id
  iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
  iae.setDistP1((int)0.1);// mapped by parm1
  iae.setDistP2((int)0.5); //mapped by parm2
  iae.addCond("true");
  iae.addToQueue("Q_A2");// mapped by next dead
  iae.addFromQueue("Q_CONTROL_ALG");// mapped by prev dead
  iae.addToResource("SCCI_MODULE");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("SCCI_MODULE");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_A2.2"); //mapped by act id
  iae.setServiceDist(ActiveEntry.POISSON);// mapped by stat type
  iae.setDistP1((int)1.0);// mapped by parm1
  iae.addCond("true");
  iae.addToQueue("Q_A2");// mapped by next dead
  iae.addFromQueue("Q_GENERATE_API_DATA");// mapped by prev dead
  iae.addToResource("SCCI_MODULE");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("SCCI_MODULE");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_A3"); //mapped by act id
  iae.setServiceDist(ActiveEntry.NEGEXP);// mapped by stat type
  iae.setDistP1((int)20);// mapped by parm1
  iae.addCond("true");
  iae.addToQueue("Q_A3");// mapped by next dead
  iae.addFromQueue("Q_A2");// mapped by prev dead
  iae.addToResource("TRAFFIC_LIGHTS");// mapped by next resource dead
  iae.addResourceQty(new Integer(2));// mapped by init on resource dead
  iae.addFromResource("TRAFFIC_LIGHTS");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_FB1"); //mapped by act id
  iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
  iae.setDistP1((int)1.0);// mapped by parm1
  iae.setDistP2((int)3.0); //mapped by parm2
  iae.addCond("true");
  iae.addToQueue("Q_FB1");// mapped by next dead
  iae.addFromQueue("Q_FB6");// mapped by prev dead
  iae.addToResource("SCCI_MODULE");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("SCCI_MODULE");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_FB2"); //mapped by act id
  iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
  iae.setDistP1((int)0);// mapped by parm1
  iae.setDistP2((int)1.0); //mapped by parm2
  iae.addCond("true");
  iae.addToQueue("Q_FB2");// mapped by next dead
  iae.addFromQueue("Q_A3");// mapped by prev dead
  iae.addToResource("INTERSECTION");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("INTERSECTION");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_FB3"); //mapped by act id
  iae.setServiceDist(ActiveEntry.NORMAL);// mapped by stat type
  iae.setDistP1((int)1.25);// mapped by parm1
  iae.setDistP2((int)1.0); //mapped by parm2
  iae.addCond("true");
  iae.addToQueue("Q_FB3");// mapped by next dead
  iae.addFromQueue("Q_FB2");// mapped by prev dead
  iae.addToResource("P_TRAFFIC_SENSOR_1");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("P_TRAFFIC_SENSOR_1");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_FB4"); //mapped by act id
  iae.setServiceDist(ActiveEntry.NEGEXP);// mapped by stat type
  iae.setDistP1((int)1.2);// mapped by parm1
  iae.addCond("true");
  iae.addToQueue("Q_FB4");// mapped by next dead
  iae.addFromQueue("Q_FB3");// mapped by prev dead
  iae.addToResource("P_TRAFFIC_SENSOR_2");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("P_TRAFFIC_SENSOR_2");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_FB5"); //mapped by act id
  iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
  iae.setDistP1((int)1);// mapped by parm1
  iae.setDistP2((int)3); //mapped by parm2
  iae.addCond("true");
  iae.addToQueue("Q_FB5");// mapped by next dead
  iae.addFromQueue("Q_FB4");// mapped by prev dead
  iae.addToResource("N_TRAFFIC_SENSOR_1");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("N_TRAFFIC_SENSOR_1");// mapped by prev resource dead
  man.AddActiveState(iae);
  
  iae = new InternalActiveEntry(true); //isn't router
  iae.SetId( "ACT_FB6"); //mapped by act id
  iae.setServiceDist(ActiveEntry.NEGEXP);// mapped by stat type
  iae.setDistP1((int)2);// mapped by parm1
  iae.addCond("true");
  iae.addToQueue("Q_FB6");// mapped by next dead
  iae.addFromQueue("Q_FB5");// mapped by prev dead
  iae.addToResource("N_TRAFFIC_SENSOR_2");// mapped by next resource dead
  iae.addResourceQty(new Integer(1));// mapped by init on resource dead
  iae.addFromResource("N_TRAFFIC_SENSOR_2");// mapped by prev resource dead
  man.AddActiveState(iae);
  

  //observers

  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_A1");//observer queue
  oe.SetId("Q_A1_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_A2");//observer queue
  oe.SetId("Q_A2_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_A3");//observer queue
  oe.SetId("Q_A3_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB1");//observer queue
  oe.SetId("Q_FB1_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB2");//observer queue
  oe.SetId("Q_FB2_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB3");//observer queue
  oe.SetId("Q_FB3_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB4");//observer queue
  oe.SetId("Q_FB4_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB5");//observer queue
  oe.SetId("Q_FB5_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB6");//observer queue
  oe.SetId("Q_FB6_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_GENERATE_CONTROL_ACTION");//observer queue
  oe.SetId("Q_GEN_CONTROL_ACTION_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_GENERATE_API_DATA");//observer queue
  oe.SetId("Q_GEN_API_DATA_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_CONTROL_ALG");//observer queue
  oe.SetId("Q_CONTROL_ALG_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"GENERATE_CONTROL_ACTION");
  oe.SetId("GEN_CONTROL_ACTION_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);

  eae = (ExternalActiveEntry)man.GetActiveState("GENERATE_CONTROL_ACTION");
  eae.setObsid("GEN_CONTROL_ACTION_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"GENERATE_API");
  oe.SetId("GEN_API_DATA_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);

  eae = (ExternalActiveEntry)man.GetActiveState("GENERATE_API");
  eae.setObsid("GEN_API_DATA_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_A1");
  oe.SetId("ACT_A1_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_A1");
  iae.setObsid("ACT_A1_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_A2.1");
  oe.SetId("ACT_A2.1_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_A2.1");
  iae.setObsid("ACT_A2.1_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_A2.2");
  oe.SetId("ACT_A2.2_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_A2.2");
  iae.setObsid("ACT_A2.2_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_A3");
  oe.SetId("ACT_A3_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_A3");
  iae.setObsid("ACT_A3_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_FB1");
  oe.SetId("ACT_FB1_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_FB1");
  iae.setObsid("ACT_FB1_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_FB2");
  oe.SetId("ACT_FB2_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_FB2");
  iae.setObsid("ACT_FB2_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_FB3");
  oe.SetId("ACT_FB3_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_FB3");
  iae.setObsid("ACT_FB3_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_FB4");
  oe.SetId("ACT_FB4_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_FB4");
  iae.setObsid("ACT_FB4_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_FB5");
  oe.SetId("ACT_FB5_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_FB5");
  iae.setObsid("ACT_FB5_OBS");
  
  oe= new ObserverEntry(ObserverEntry.ACTIVE,"ACT_FB6");
  oe.SetId("ACT_FB6_OBS");
  oe.setName(oe.GetId());
  man.AddObserver(oe);
  
  

  iae = (InternalActiveEntry)man.GetActiveState("ACT_FB6");
  iae.setObsid("ACT_FB6_OBS");
  

  //generate the model

  if (man.GenerateModel())
     System.out.println("\nModel successfuly generated!");
  else
  {
     System.out.println("\nThere was an errors during the model generation!");
     System.out.println("Exiting...");
     return;
  }

  //start the simulation

  System.out.println("Starting the simulation. Simulation wil run unitl time=500");

  man.ExecuteSimulation(500);

  while (!man.Finished())
  {
   try
   {
    Thread.sleep(1000);
   }
   catch(InterruptedException e) {break;}
  }

  System.out.println("Simulation Stopped!");

  //finally, output the results

  man.OutputSimulationResults ("SCSI.out");

  
  System.out.println("\nThat's all folks!");
 }
}